require_relative 'database'
require_relative 'seed'

namespace :db  do
  task :create do
    Database.create
    Database.migrate
  end

  task :seed do
    Seed.execute
  end

  task :drop do
    Database.drop
  end

  task :reset do
    Database.drop
    Database.create
    Database.migrate
    Seed.execute
  end
end
