//! Everything in the pack, generated from `docs/art-prompts` (the prompts that produced the
//! art) — names, sheet cell sizes and what each sheet's sixth row holds.

use crate::{CharacterInfo, Faction, Kind, PropInfo, Special, StructureInfo, TerrainInfo};

/// Units, heroes and monsters: 6 × 6 cell sheets (idle, walk, attack, hurt, death, special).
pub static CHARACTERS: &[CharacterInfo] = &[
    CharacterInfo {
        id: "unit_elf_archer",
        name: "Archer",
        kind: Kind::Unit,
        faction: Faction::Elf,
        cell: 48,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/units/unit_elf_archer.png"),
    },
    CharacterInfo {
        id: "unit_elf_bear",
        name: "Druid Bear",
        kind: Kind::Unit,
        faction: Faction::Elf,
        cell: 64,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_elf_bear.png"),
    },
    CharacterInfo {
        id: "unit_elf_dryad",
        name: "Dryad",
        kind: Kind::Unit,
        faction: Faction::Elf,
        cell: 64,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/units/unit_elf_dryad.png"),
    },
    CharacterInfo {
        id: "unit_elf_hippogryph",
        name: "Hippogryph Rider",
        kind: Kind::Unit,
        faction: Faction::Elf,
        cell: 64,
        special: Special::Shoot,
        flying: true,
        png: include_bytes!("../assets/units/unit_elf_hippogryph.png"),
    },
    CharacterInfo {
        id: "unit_elf_sentinel",
        name: "Sentinel",
        kind: Kind::Unit,
        faction: Faction::Elf,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_elf_sentinel.png"),
    },
    CharacterInfo {
        id: "unit_elf_treant",
        name: "Treant",
        kind: Kind::Unit,
        faction: Faction::Elf,
        cell: 64,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_elf_treant.png"),
    },
    CharacterInfo {
        id: "unit_elf_wisp",
        name: "Wisp",
        kind: Kind::Unit,
        faction: Faction::Elf,
        cell: 48,
        special: Special::Work,
        flying: true,
        png: include_bytes!("../assets/units/unit_elf_wisp.png"),
    },
    CharacterInfo {
        id: "unit_human_archer",
        name: "Archer",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 48,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/units/unit_human_archer.png"),
    },
    CharacterInfo {
        id: "unit_human_footman",
        name: "Footman",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_human_footman.png"),
    },
    CharacterInfo {
        id: "unit_human_griffon",
        name: "Griffon Rider",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 64,
        special: Special::Attack2,
        flying: true,
        png: include_bytes!("../assets/units/unit_human_griffon.png"),
    },
    CharacterInfo {
        id: "unit_human_knight",
        name: "Knight",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 64,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_human_knight.png"),
    },
    CharacterInfo {
        id: "unit_human_peasant",
        name: "Peasant",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 48,
        special: Special::Work,
        flying: false,
        png: include_bytes!("../assets/units/unit_human_peasant.png"),
    },
    CharacterInfo {
        id: "unit_human_priest",
        name: "Priest",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 48,
        special: Special::Cast,
        flying: false,
        png: include_bytes!("../assets/units/unit_human_priest.png"),
    },
    CharacterInfo {
        id: "unit_human_rifleman",
        name: "Rifleman",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 48,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/units/unit_human_rifleman.png"),
    },
    CharacterInfo {
        id: "unit_human_sorceress",
        name: "Sorceress",
        kind: Kind::Unit,
        faction: Faction::Human,
        cell: 48,
        special: Special::Cast,
        flying: false,
        png: include_bytes!("../assets/units/unit_human_sorceress.png"),
    },
    CharacterInfo {
        id: "unit_orc_axethrower",
        name: "Axe Thrower",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 48,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/units/unit_orc_axethrower.png"),
    },
    CharacterInfo {
        id: "unit_orc_grunt",
        name: "Grunt",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_orc_grunt.png"),
    },
    CharacterInfo {
        id: "unit_orc_ogre",
        name: "Ogre Brute",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 64,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_orc_ogre.png"),
    },
    CharacterInfo {
        id: "unit_orc_peon",
        name: "Peon",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 48,
        special: Special::Work,
        flying: false,
        png: include_bytes!("../assets/units/unit_orc_peon.png"),
    },
    CharacterInfo {
        id: "unit_orc_shaman",
        name: "Shaman",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 48,
        special: Special::Cast,
        flying: false,
        png: include_bytes!("../assets/units/unit_orc_shaman.png"),
    },
    CharacterInfo {
        id: "unit_orc_witchdoctor",
        name: "Witch Doctor",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 48,
        special: Special::Cast,
        flying: false,
        png: include_bytes!("../assets/units/unit_orc_witchdoctor.png"),
    },
    CharacterInfo {
        id: "unit_orc_wolfrider",
        name: "Wolf Rider",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 64,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/units/unit_orc_wolfrider.png"),
    },
    CharacterInfo {
        id: "unit_orc_wyvern",
        name: "Wyvern Rider",
        kind: Kind::Unit,
        faction: Faction::Orc,
        cell: 64,
        special: Special::Shoot,
        flying: true,
        png: include_bytes!("../assets/units/unit_orc_wyvern.png"),
    },
    CharacterInfo {
        id: "hero_elf_keeper",
        name: "Keeper of the Grove",
        kind: Kind::Hero,
        faction: Faction::Elf,
        cell: 64,
        special: Special::Cast,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_elf_keeper.png"),
    },
    CharacterInfo {
        id: "hero_elf_priestess",
        name: "Moon Priestess",
        kind: Kind::Hero,
        faction: Faction::Elf,
        cell: 64,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_elf_priestess.png"),
    },
    CharacterInfo {
        id: "hero_elf_warden",
        name: "Warden",
        kind: Kind::Hero,
        faction: Faction::Elf,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_elf_warden.png"),
    },
    CharacterInfo {
        id: "hero_human_archmage",
        name: "Archmage",
        kind: Kind::Hero,
        faction: Faction::Human,
        cell: 48,
        special: Special::Cast,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_human_archmage.png"),
    },
    CharacterInfo {
        id: "hero_human_paladin",
        name: "Paladin",
        kind: Kind::Hero,
        faction: Faction::Human,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_human_paladin.png"),
    },
    CharacterInfo {
        id: "hero_human_ranger",
        name: "Ranger Lord",
        kind: Kind::Hero,
        faction: Faction::Human,
        cell: 48,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_human_ranger.png"),
    },
    CharacterInfo {
        id: "hero_orc_chieftain",
        name: "Blood Chieftain",
        kind: Kind::Hero,
        faction: Faction::Orc,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_orc_chieftain.png"),
    },
    CharacterInfo {
        id: "hero_orc_farseer",
        name: "Farseer",
        kind: Kind::Hero,
        faction: Faction::Orc,
        cell: 64,
        special: Special::Cast,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_orc_farseer.png"),
    },
    CharacterInfo {
        id: "hero_orc_warlord",
        name: "Warlord",
        kind: Kind::Hero,
        faction: Faction::Orc,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/heroes/hero_orc_warlord.png"),
    },
    CharacterInfo {
        id: "monster_bandit",
        name: "Bandit",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_bandit.png"),
    },
    CharacterInfo {
        id: "monster_bear",
        name: "Bear",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_bear.png"),
    },
    CharacterInfo {
        id: "monster_dragon",
        name: "Young Dragon",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 96,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_dragon.png"),
    },
    CharacterInfo {
        id: "monster_fishman",
        name: "Fishman",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_fishman.png"),
    },
    CharacterInfo {
        id: "monster_golem",
        name: "Rock Golem",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 64,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_golem.png"),
    },
    CharacterInfo {
        id: "monster_harpy",
        name: "Harpy",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: true,
        png: include_bytes!("../assets/monsters/monster_harpy.png"),
    },
    CharacterInfo {
        id: "monster_skeleton",
        name: "Skeleton Warrior",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_skeleton.png"),
    },
    CharacterInfo {
        id: "monster_skeleton_archer",
        name: "Skeleton Archer",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Shoot,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_skeleton_archer.png"),
    },
    CharacterInfo {
        id: "monster_slime",
        name: "Slime",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_slime.png"),
    },
    CharacterInfo {
        id: "monster_spider",
        name: "Giant Spider",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_spider.png"),
    },
    CharacterInfo {
        id: "monster_troll",
        name: "Forest Troll",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_troll.png"),
    },
    CharacterInfo {
        id: "monster_wolf",
        name: "Wolf",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_wolf.png"),
    },
    CharacterInfo {
        id: "monster_zombie",
        name: "Zombie",
        kind: Kind::Monster,
        faction: Faction::Monster,
        cell: 48,
        special: Special::Attack2,
        flying: false,
        png: include_bytes!("../assets/monsters/monster_zombie.png"),
    },
];

/// Buildings: 4 × 2 cell sheets (4-frame idle; construction, damaged, ruined).
pub static STRUCTURES: &[StructureInfo] = &[
    StructureInfo {
        id: "building_elf_ancientofwar",
        name: "Ancient of War",
        faction: Faction::Elf,
        cell: (96, 96),
        png: include_bytes!("../assets/structures/building_elf_ancientofwar.png"),
    },
    StructureInfo {
        id: "building_elf_house",
        name: "Elven House",
        faction: Faction::Elf,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_elf_house.png"),
    },
    StructureInfo {
        id: "building_elf_huntershall",
        name: "Hunter's Hall",
        faction: Faction::Elf,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_elf_huntershall.png"),
    },
    StructureInfo {
        id: "building_elf_moonwell",
        name: "Moon Well",
        faction: Faction::Elf,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_elf_moonwell.png"),
    },
    StructureInfo {
        id: "building_elf_sanctum",
        name: "Arcane Sanctum",
        faction: Faction::Elf,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_elf_sanctum.png"),
    },
    StructureInfo {
        id: "building_elf_tower",
        name: "Ancient Tower",
        faction: Faction::Elf,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_elf_tower.png"),
    },
    StructureInfo {
        id: "building_elf_treeoflife",
        name: "Tree of Life",
        faction: Faction::Elf,
        cell: (96, 96),
        png: include_bytes!("../assets/structures/building_elf_treeoflife.png"),
    },
    StructureInfo {
        id: "building_human_barracks",
        name: "Barracks",
        faction: Faction::Human,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_human_barracks.png"),
    },
    StructureInfo {
        id: "building_human_blacksmith",
        name: "Blacksmith",
        faction: Faction::Human,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_human_blacksmith.png"),
    },
    StructureInfo {
        id: "building_human_castle",
        name: "Castle",
        faction: Faction::Human,
        cell: (96, 96),
        png: include_bytes!("../assets/structures/building_human_castle.png"),
    },
    StructureInfo {
        id: "building_human_church",
        name: "Church",
        faction: Faction::Human,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_human_church.png"),
    },
    StructureInfo {
        id: "building_human_farm",
        name: "Farm",
        faction: Faction::Human,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_human_farm.png"),
    },
    StructureInfo {
        id: "building_human_guardtower",
        name: "Guard Tower",
        faction: Faction::Human,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_human_guardtower.png"),
    },
    StructureInfo {
        id: "building_human_house",
        name: "House",
        faction: Faction::Human,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_human_house.png"),
    },
    StructureInfo {
        id: "building_human_lumbermill",
        name: "Lumber Mill",
        faction: Faction::Human,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_human_lumbermill.png"),
    },
    StructureInfo {
        id: "building_human_magetower",
        name: "Mage Tower",
        faction: Faction::Human,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_human_magetower.png"),
    },
    StructureInfo {
        id: "building_human_townhall",
        name: "Town Hall",
        faction: Faction::Human,
        cell: (96, 96),
        png: include_bytes!("../assets/structures/building_human_townhall.png"),
    },
    StructureInfo {
        id: "building_human_windmill",
        name: "Windmill",
        faction: Faction::Human,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_human_windmill.png"),
    },
    StructureInfo {
        id: "building_neutral_chest",
        name: "Treasure Chest",
        faction: Faction::Neutral,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_neutral_chest.png"),
    },
    StructureInfo {
        id: "building_neutral_goldmine",
        name: "Gold Mine",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_goldmine.png"),
    },
    StructureInfo {
        id: "building_neutral_market",
        name: "Market",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_market.png"),
    },
    StructureInfo {
        id: "building_neutral_portal",
        name: "Portal",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_portal.png"),
    },
    StructureInfo {
        id: "building_neutral_quarry",
        name: "Stone Quarry",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_quarry.png"),
    },
    StructureInfo {
        id: "building_neutral_ruins",
        name: "Ruins",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_ruins.png"),
    },
    StructureInfo {
        id: "building_neutral_sawmill",
        name: "Sawmill",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_sawmill.png"),
    },
    StructureInfo {
        id: "building_neutral_shrine",
        name: "Shrine",
        faction: Faction::Neutral,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_neutral_shrine.png"),
    },
    StructureInfo {
        id: "building_neutral_tavern",
        name: "Tavern",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_tavern.png"),
    },
    StructureInfo {
        id: "building_neutral_village",
        name: "Village Houses",
        faction: Faction::Neutral,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_neutral_village.png"),
    },
    StructureInfo {
        id: "building_neutral_well",
        name: "Well",
        faction: Faction::Neutral,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_neutral_well.png"),
    },
    StructureInfo {
        id: "building_orc_barracks",
        name: "Barracks",
        faction: Faction::Orc,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_orc_barracks.png"),
    },
    StructureInfo {
        id: "building_orc_burrow",
        name: "Burrow",
        faction: Faction::Orc,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_orc_burrow.png"),
    },
    StructureInfo {
        id: "building_orc_forge",
        name: "Forge",
        faction: Faction::Orc,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_orc_forge.png"),
    },
    StructureInfo {
        id: "building_orc_greathall",
        name: "Great Hall",
        faction: Faction::Orc,
        cell: (96, 96),
        png: include_bytes!("../assets/structures/building_orc_greathall.png"),
    },
    StructureInfo {
        id: "building_orc_hut",
        name: "Hut",
        faction: Faction::Orc,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_orc_hut.png"),
    },
    StructureInfo {
        id: "building_orc_spiritlodge",
        name: "Spirit Lodge",
        faction: Faction::Orc,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_orc_spiritlodge.png"),
    },
    StructureInfo {
        id: "building_orc_stronghold",
        name: "Stronghold",
        faction: Faction::Orc,
        cell: (96, 96),
        png: include_bytes!("../assets/structures/building_orc_stronghold.png"),
    },
    StructureInfo {
        id: "building_orc_warmill",
        name: "War Mill",
        faction: Faction::Orc,
        cell: (64, 64),
        png: include_bytes!("../assets/structures/building_orc_warmill.png"),
    },
    StructureInfo {
        id: "building_orc_watchtower",
        name: "Watch Tower",
        faction: Faction::Orc,
        cell: (48, 64),
        png: include_bytes!("../assets/structures/building_orc_watchtower.png"),
    },
];

/// Ground materials: four 32² top variants over four 32×16 cliff tiles (animated ones: two
/// variants of four frames each).
pub static TERRAIN: &[TerrainInfo] = &[
    TerrainInfo {
        id: "terrain_ash",
        name: "ash",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_ash.png"),
    },
    TerrainInfo {
        id: "terrain_desert",
        name: "desert",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_desert.png"),
    },
    TerrainInfo {
        id: "terrain_dirt",
        name: "dirt",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_dirt.png"),
    },
    TerrainInfo {
        id: "terrain_elf_moss",
        name: "elf_moss",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_elf_moss.png"),
    },
    TerrainInfo {
        id: "terrain_farmland",
        name: "farmland",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_farmland.png"),
    },
    TerrainInfo {
        id: "terrain_forest_floor",
        name: "forest_floor",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_forest_floor.png"),
    },
    TerrainInfo {
        id: "terrain_grass",
        name: "grass",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_grass.png"),
    },
    TerrainInfo {
        id: "terrain_ice",
        name: "ice",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_ice.png"),
    },
    TerrainInfo {
        id: "terrain_lava",
        name: "lava",
        animated: true,
        png: include_bytes!("../assets/terrain/terrain_lava.png"),
    },
    TerrainInfo {
        id: "terrain_meadow",
        name: "meadow",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_meadow.png"),
    },
    TerrainInfo {
        id: "terrain_orc_wasteland",
        name: "orc_wasteland",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_orc_wasteland.png"),
    },
    TerrainInfo {
        id: "terrain_road_cobble",
        name: "road_cobble",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_road_cobble.png"),
    },
    TerrainInfo {
        id: "terrain_road_dirt",
        name: "road_dirt",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_road_dirt.png"),
    },
    TerrainInfo {
        id: "terrain_rock",
        name: "rock",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_rock.png"),
    },
    TerrainInfo {
        id: "terrain_sand",
        name: "sand",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_sand.png"),
    },
    TerrainInfo {
        id: "terrain_seabed",
        name: "seabed",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_seabed.png"),
    },
    TerrainInfo {
        id: "terrain_snow",
        name: "snow",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_snow.png"),
    },
    TerrainInfo {
        id: "terrain_swamp",
        name: "swamp",
        animated: false,
        png: include_bytes!("../assets/terrain/terrain_swamp.png"),
    },
    TerrainInfo {
        id: "terrain_water",
        name: "water",
        animated: true,
        png: include_bytes!("../assets/terrain/terrain_water.png"),
    },
];

/// Upright props: four cells per sheet.
pub static PROPS: &[PropInfo] = &[
    PropInfo {
        id: "props_bushes_flowers",
        cell: (32, 32),
        png: include_bytes!("../assets/terrain/props_bushes_flowers.png"),
    },
    PropInfo { id: "props_mountains", cell: (64, 64), png: include_bytes!("../assets/terrain/props_mountains.png") },
    PropInfo { id: "props_rocks", cell: (32, 32), png: include_bytes!("../assets/terrain/props_rocks.png") },
    PropInfo {
        id: "props_trees_birch",
        cell: (32, 48),
        png: include_bytes!("../assets/terrain/props_trees_birch.png"),
    },
    PropInfo { id: "props_trees_dead", cell: (32, 48), png: include_bytes!("../assets/terrain/props_trees_dead.png") },
    PropInfo { id: "props_trees_elf", cell: (32, 48), png: include_bytes!("../assets/terrain/props_trees_elf.png") },
    PropInfo { id: "props_trees_oak", cell: (32, 48), png: include_bytes!("../assets/terrain/props_trees_oak.png") },
    PropInfo { id: "props_trees_palm", cell: (32, 48), png: include_bytes!("../assets/terrain/props_trees_palm.png") },
    PropInfo { id: "props_trees_pine", cell: (32, 48), png: include_bytes!("../assets/terrain/props_trees_pine.png") },
    PropInfo { id: "props_trees_snow", cell: (32, 48), png: include_bytes!("../assets/terrain/props_trees_snow.png") },
];

/// Fire, smoke, embers and burn decals.
pub static FX_FIRE: &[u8] = include_bytes!("../assets/terrain/fx_fire.png");

/// The style bible every asset was drawn to.
pub static STYLE_REFERENCE: &[u8] = include_bytes!("../assets/style_reference.png");
