// humanoid character configs. expects X, G (rig). returns {name:{cfg,cell}}
const {P,Img,shadeBlob,line}=X; const {R,box,blobClip,strip,pt}=G;
const H={
  helmet:(ramp,o={})=>(img,T,ex,ey)=>{ blobClip(img,T.hx,T.hy-0.5,T.hr+0.6,T.hr+0.3,ramp.concat([P.g5]),(x,y)=>y<ey-(o.low?0:1)||x<ex-2); for(let x=Math.round(T.hx-T.hr);x<=Math.round(T.hx+T.hr);x++) if(img.get(x,ey-1-(o.low?-1:0))) img.set(x,ey-1-(o.low?-1:0),ramp[0]); if(o.nasal){ img.set(ex+1,ey,ramp[1]); img.set(ex+1,ey+1,ramp[1]); } if(o.crest){ for(let k=0;k<4;k++) img.set(Math.round(T.hx)-k,Math.round(T.hy-T.hr)-1+Math.floor(k/2),o.crest[k%2?1:2]); } if(o.horns){ const top=Math.round(T.hy-T.hr); img.set(Math.round(T.hx)-3,top,P.g5); img.set(Math.round(T.hx)-4,top-1,P.g5); img.set(Math.round(T.hx)+3,top,P.g4); img.set(Math.round(T.hx)+4,top-1,P.g5);} },
  hood:(ramp,o={})=>(img,T,ex,ey)=>{ blobClip(img,T.hx-0.5,T.hy-0.5,T.hr+1,T.hr+0.9,ramp.concat([null]),(x,y)=>!(x>=ex-2&&y>=ey-1&&y<=ey+3)); for(let y=ey-1;y<=ey+3;y++) if(img.get(ex-3,y)) img.set(ex-3,y,o.lining?o.lining[1]:ramp[0]); if(o.lining){ img.set(ex-2,ey-2,o.lining[2]); img.set(ex-1,ey-2,o.lining[1]); img.set(ex,ey-2,o.lining[1]); } if(o.mask){ for(let x=ex-2;x<=ex+2;x++){ if(img.get(x,ey+1)) img.set(x,ey+1,o.mask[2]); if(img.get(x,ey+2)) img.set(x,ey+2,o.mask[1]); } } if(o.tail){ const bx=Math.round(T.hx-T.hr); for(let k=0;k<4;k++){ img.set(bx-1,Math.round(T.hy)+k,ramp[1]); img.set(bx,Math.round(T.hy)+k+1,ramp[0]); } } },
  hair:(ramp,o={})=>(img,T,ex,ey)=>{ if(!o.noCap) blobClip(img,T.hx-0.4,T.hy-0.6,T.hr+0.5,T.hr+0.2,ramp.concat([null]),(x,y)=>y<ey-1-(o.short?1:0)||(x<ex-3 && y<ey+(o.long?6:2))); if(o.long){ const bx=Math.round(T.hx-T.hr); for(let k=0;k<o.long;k++){ img.set(bx,Math.round(T.hy)+k,ramp[1]); img.set(bx+1,Math.round(T.hy)+k,ramp[2]); img.set(bx-1,Math.round(T.hy)+k+1,ramp[0]); } } if(o.topknot){ const tx=Math.round(T.hx)-1, ty=Math.round(T.hy-T.hr)-1; box(img,tx-1,ty-2,3,3,ramp); img.set(tx,ty-3,ramp[1]); } if(o.mohawk){ for(let k=-3;k<=2;k++) { img.set(Math.round(T.hx)+k,Math.round(T.hy-T.hr)-1-(k<1?1:0),ramp[2]); img.set(Math.round(T.hx)+k,Math.round(T.hy-T.hr),ramp[1]); } } },
  beard:(ramp,len=3)=>(img,T,ex,ey)=>{ for(let j=0;j<len;j++) for(let i=-3+Math.floor(j/2);i<=2-Math.floor(j/3);i++) img.set(ex-1+i,ey+2+j,i<-1?ramp[2]:(i>0?ramp[0]:ramp[1])); img.set(ex+1,ey+1,ramp[1]); img.set(ex-3,ey+1,ramp[1]); },
  pointHat:(ramp,o={})=>(img,T,ex,ey)=>{ const top=Math.round(T.hy-T.hr)+1; for(let j=0;j<(o.h||8);j++){ const w=Math.max(0,3.5-j*0.45); for(let i=-w;i<=w;i+=1) img.set(Math.round(T.hx)+Math.round(i)-Math.round(j*j*0.06),top-j,i<-0.8?ramp[2]:(i>0.8?ramp[0]:ramp[1])); } for(let x=Math.round(T.hx-T.hr)-1;x<=Math.round(T.hx+T.hr)+1;x++) img.set(x,top+1,x<T.hx?ramp[2]:ramp[1]); if(o.band) for(let x=Math.round(T.hx)-3;x<=Math.round(T.hx)+3;x++) img.set(x,top,o.band[1]); },
  strawHat:(img,T,ex,ey)=>{ const top=Math.round(T.hy-T.hr)+1; box(img,Math.round(T.hx)-3,top-2,6,3,[P.y1,P.y2,P.y3]); for(let x=Math.round(T.hx-T.hr)-2;x<=Math.round(T.hx+T.hr)+2;x++) img.set(x,top+1,x<T.hx?P.y3:P.y2); },
  cap:(ramp)=>(img,T,ex,ey)=>{ blobClip(img,T.hx-0.5,T.hy-0.8,T.hr+0.4,T.hr,ramp.concat([null]),(x,y)=>y<ey-1); img.set(ex+1,ey-1,ramp[0]); img.set(ex+2,ey-1,ramp[0]); },
  skull:(img,T,ex,ey)=>{ img.set(ex,ey,P.DS); img.set(ex-1,ey,P.DS); img.set(ex,ey+1,P.g2); img.set(ex+1,ey+2,P.g3); img.set(ex-1,ey+2,P.g2); img.set(ex,ey+2,P.DS); img.set(ex,ey,P.r3); },
};
const ribs=(img,T)=>{ for(let j=1;j<T.tH-1;j+=2) for(let i=1;i<T.tw-1;i++) img.set(T.tL+i,T.tTop+j,P.DS); for(let j=0;j<T.tH;j++) img.set(T.tL+Math.floor(T.tw/2),T.tTop+j,P.g4); for(let i=0;i<T.tw;i++){ if(i<2||i>T.tw-3){ for(let j=T.tH-3;j<T.tH;j++) img.set(T.tL+i,T.tTop+j,null);} } };
const tabard=(ramp,w=4,o={})=>(img,T)=>{ const x0=T.tL+Math.floor(T.tw/2)-Math.floor(w/2)+1; for(let y=T.tTop+(o.top||2);y<=T.hipY+(o.long||2);y++) for(let i=0;i<w;i++) img.set(x0+i,y,i===0?ramp[2]:(i===w-1?ramp[0]:ramp[1])); if(o.trim) for(let i=0;i<w;i++) img.set(x0+i,T.hipY+(o.long||2),o.trim[1]); };
const sash=(ramp)=>(img,T)=>{ for(let k=0;k<T.tw;k++){ const y=T.tTop+1+Math.round(k*(T.tH-2)/T.tw); img.set(T.tL+k,y,ramp[2]); img.set(T.tL+k,y+1,ramp[1]); } };
const loin=(ramp,len=4)=>(img,T)=>{ const x0=T.tL+Math.floor(T.tw/2)-1; for(let j=0;j<len;j++) for(let i=0;i<4-Math.floor(j/2);i++) img.set(x0+i,T.hipY+j,i===0?ramp[2]:ramp[1]); };
const spikePad=(ramp)=>(img,T)=>{ const x=T.shX, y=T.shY-1; shadeBlob(img,x,y,3*T.S,2.4*T.S,ramp.concat([P.g5])); img.set(x-1,y-3,P.g4); img.set(x,y-4,P.g5); img.set(x+2,y-3,P.g4); img.set(x+3,y-4,P.g5); };
const roundPad=(ramp)=>(img,T)=>shadeBlob(img,T.shX,T.shY-1,2.6*T.S,2*T.S,ramp);
const compose=(...fs)=>(img,T,a,b)=>fs.forEach(f=>f&&f(img,T,a,b));
const quiver=(img,T)=>{ const x=T.tL+1,y=T.tTop-3; strip(img,x,y,1.9,0,9,1.1,R.leather); img.set(x-1,y-1,P.g5); img.set(x+1,y-2,P.g5); img.set(x,y-2,P.r3); };
const banner=(img,T)=>{ const x=T.tL, y0=T.tTop-14; for(let y=y0;y<=T.tTop+4;y++) img.set(x,y,y===y0?P.y3:P.b3); for(let j=0;j<8;j++) for(let i=1;i<=6-(j>5?j-5:0);i++) img.set(x-i,y0+1+j+Math.floor(i/3),i<2?P.m4:(j>5?P.m2:P.m3)); };
const drum=(img,T)=>{ shadeBlob(img,T.tL,T.tTop+2,3.5,3,[P.b2,P.b3,P.b5,null]); for(let y=T.tTop-1;y<T.tTop+5;y++) img.set(T.tL-3,y,P.r2); };
const C={};
const U=48;
C.unit_human_footman={cell:U,cfg:{anim:'melee',skin:R.skin,torso:R.chain,sleeve:R.chain,pants:R.blue,boots:R.leather,belt:R.leather,weapon:'sword',wOpt:{len:9},shield:'kite',deco:tabard([P.w1,P.w2,P.w3],4,{trim:R.gold}),head:H.helmet(R.steel,{nasal:1}),pad:roundPad(R.steel.slice(0,3).concat([null]))}};
C.unit_human_archer={cell:U,cfg:{anim:'bow',skin:R.skin,torso:R.lleather,sleeve:R.green,pants:R.green,boots:R.leather,belt:R.leather,weapon:'bow',wOpt:{h:8},head:compose(H.hood(R.team,{tail:1})),backItem:quiver,bulk:0.9}};
C.unit_human_peasant={cell:U,cfg:{anim:'melee',skin:R.skin,torso:R.leather,pants:R.lleather,boots:R.leather,belt:[P.b1,P.b1,P.b2],weapon:'pick',head:compose(H.hair(R.hair_brown,{short:1}),H.strawHat),deco:(img,T)=>box(img,T.tL+3,T.tTop+2,3,3,R.team),bulk:0.9}};
C.unit_human_priest={cell:U,cfg:{anim:'caster',skin:R.skin,torso:R.white,pants:R.white,boots:R.leather,robe:R.white,robeTrim:R.gold,weapon:'staff',wOpt:{len:9,top:'sun'},head:compose(H.hair(R.hair_brown,{short:1})),deco:(img,T)=>{ for(let y=T.tTop;y<=T.gy-2;y++){ img.set(T.tL+2,y,P.m3); img.set(T.tL+3,y,P.m2);} },castColor:[P.y3,P.g5],belt:R.gold}};
C.unit_human_rifleman={cell:U,cfg:{anim:'gun',skin:R.skin,torso:R.lleather,pants:R.leather,boots:R.dark,belt:R.leather,legLen:0.7,bulk:1.15,headScale:1.05,weapon:'musket',twoHand:5,head:compose(H.cap(R.leather),H.beard(R.hair_brown,4)),deco:(img,T)=>{ for(let i=1;i<T.tw-1;i++){ img.set(T.tL+i,T.tTop,P.m3); img.set(T.tL+i,T.tTop+1,i<4?P.m4:P.m2);} }}};
C.unit_human_sorceress={cell:U,cfg:{anim:'caster',skin:R.skin,torso:R.blue,pants:R.blue,boots:R.leather,robe:[P.w1,P.w2,P.w3],weapon:null,head:compose(H.hair(R.hair_blond,{long:5}),H.pointHat(R.blue,{band:R.gold,h:9})),deco:(img,T)=>{ for(let i=0;i<T.tw;i++) img.set(T.tL+i,T.tTop,i<3?P.m4:P.m3); for(let i=2;i<T.tw-2;i++) img.set(T.tL+i,T.tTop+1,P.m2); },bulk:0.85,animOverride:{idle:[{bob:0,cast:1,armA:0.6},{bob:0,armA:0.6},{bob:1,cast:1,armA:0.6},{bob:1,armA:0.6}]},castColor:[P.t2,P.t3]}};
C.unit_orc_grunt={cell:U,cfg:{anim:'melee',skin:R.orc,torso:R.orc,sleeve:R.orc,pants:R.leather,boots:R.leather,belt:R.leather,bulk:1.25,weapon:'axe',wOpt:{len:12,head:5},tusks:1,brow:1,eye:P.r3,head:H.hair(R.hair_black,{mohawk:1,noCap:1}),pad:spikePad(R.rust),deco:compose(loin(R.team),(img,T)=>{ for(let j=0;j<2;j++) for(let i=0;i<3;i++) img.set(T.shX-1+i,T.shY+4+j,j?P.m2:P.m3); })}};
C.unit_orc_peon={cell:U,cfg:{anim:'melee',skin:R.orc,torso:R.orc,sleeve:R.orc,pants:R.orc,boots:R.leather,belt:R.leather,bulk:1.05,hunch:2,weapon:'axe',wOpt:{len:9,head:3},tusks:1,brow:1,deco:loin(R.team,5),legLen:0.85}};
C.unit_orc_shaman={cell:U,cfg:{anim:'caster',skin:R.orc,torso:R.fur,sleeve:R.orc,pants:R.leather,boots:R.leather,belt:R.leather,weapon:'staff',wOpt:{len:11,top:'bone'},tusks:1,brow:1,hunch:1,head:compose(H.hair(R.white,{long:4}),(img,T,ex,ey)=>{ img.set(Math.round(T.hx)-4,Math.round(T.hy-T.hr),P.r3); img.set(Math.round(T.hx)-5,Math.round(T.hy-T.hr)-1,P.g5); }),deco:(img,T)=>{ for(let i=0;i<T.tw;i++){ img.set(T.tL+i,T.tTop,i<3?P.m4:P.m3); img.set(T.tL+i,T.tTop+1,P.m2);} for(let i=2;i<T.tw;i+=2) img.set(T.tL+i,T.tTop+3,i%4?P.y3:P.w4); },castColor:[P.w3,P.w5]}};
C.unit_orc_witchdoctor={cell:U,cfg:{anim:'caster',skin:R.troll,torso:R.troll,sleeve:R.troll,pants:R.leather,boots:R.leather,belt:R.leather,weapon:'staff',wOpt:{len:12,top:'skull'},tusks:2,legLen:1.1,bulk:0.85,ear:1,head:compose(H.hair(R.red,{mohawk:1,noCap:1}),(img,T,ex,ey)=>{ for(let x=ex-2;x<=ex+1;x++){ img.set(x,ey-1,P.m3); img.set(x,ey+1,P.m2);} img.set(ex,ey,P.y3); }),deco:compose(loin(R.leather),(img,T)=>{ img.set(T.tL+3,T.tTop+1,P.g5); img.set(T.tL+5,T.tTop+2,P.g5); }),castColor:[P.n4,P.n5]}};
C.unit_orc_axethrower={cell:U,cfg:{anim:'melee',skin:R.troll,torso:R.troll,sleeve:R.troll,pants:R.leather,boots:R.leather,belt:R.leather,weapon:'axe',wOpt:{len:6,head:3},tusks:2,legLen:1.2,bulk:0.8,ear:1,head:compose(H.hair(R.red,{mohawk:1,noCap:1}),(img,T,ex,ey)=>{ for(let x=Math.round(T.hx-T.hr);x<=Math.round(T.hx+T.hr);x++) if(img.get(x,ey-2)) img.set(x,ey-2,x<T.hx?P.m4:P.m2); }),deco:compose(loin(R.leather),(img,T)=>{ for(let k=0;k<2;k++){ img.set(T.tL+1+k*3,T.hipY,P.g4); img.set(T.tL+1+k*3,T.hipY+1,P.g3);} })}};
C.unit_elf_archer={cell:U,cfg:{anim:'bow',skin:R.elf,torso:R.lgreen,sleeve:R.green,pants:R.green,boots:R.leather,belt:R.leather,weapon:'bow',wOpt:{h:8,recurve:1,ramp:[P.b3,P.b4,P.b5]},ear:1,head:H.hood(R.green,{lining:R.team,tail:1}),backItem:quiver,bulk:0.85,legLen:1.1,deco:(img,T)=>{ img.set(T.tL+3,T.tTop+3,P.n4); img.set(T.tL+5,T.tTop+5,P.n4); img.set(T.tL+4,T.tTop+4,P.n5); }}};
C.unit_elf_sentinel={cell:U,cfg:{anim:'melee',skin:R.elf,torso:R.steel.slice(0,3),sleeve:R.violet,pants:R.violet,boots:R.grey,belt:R.gold,weapon:'glaive',ear:1,cape:R.team,bulk:0.85,legLen:1.1,head:H.hair(R.hair_violet,{long:6}),pad:roundPad([P.g2,P.g3,P.g5,null]),basePose:{wA:-1.2}}};
// heroes
C.hero_human_archmage={cell:U,cfg:{anim:'caster',scale:1.1,skin:R.skin,torso:R.blue,pants:R.blue,boots:R.leather,robe:R.blue,robeTrim:R.team,weapon:'staff',wOpt:{len:14,top:'crystal',glow:1},head:compose(H.hood(R.blue),H.beard(R.white,7)),deco:(img,T)=>{ for(let y=T.tTop;y<=T.gy-1;y++) img.set(T.tL+T.tw-3,y,P.m3); },castColor:[P.t2,P.t3],belt:R.team}};
C.hero_human_paladin={cell:U,cfg:{anim:'melee',scale:1.15,bulk:1.1,skin:R.skin,torso:R.steel,sleeve:R.steel,pants:R.steel,boots:R.dsteel,belt:R.gold,weapon:'hammer',wOpt:{len:11,glow:1,head:[P.g2,P.g3,P.g5]},cape:R.team,deco:tabard(R.team,5,{trim:R.gold}),head:H.hair(R.hair_blond,{short:1}),pad:roundPad([P.y1,P.y2,P.y3,P.g5]),twoHand:4}};
C.hero_human_ranger={cell:U,cfg:{anim:'bow',scale:1.12,skin:R.skin,torso:R.lleather,sleeve:R.green,pants:R.leather,boots:R.leather,belt:R.gold,weapon:'bow',wOpt:{h:10,ramp:[P.b3,P.y2,P.y3]},cape:R.green,head:H.hood(R.green,{lining:R.team,tail:1}),backItem:quiver}};
C.hero_orc_chieftain={cell:U,cfg:{anim:'melee',scale:1.15,bulk:1.35,skin:R.orc,torso:R.orc,sleeve:R.orc,pants:R.leather,boots:R.dsteel,belt:R.rust,weapon:'axe',wOpt:{len:13,head:5,double:1},twoHand:4,tusks:2,brow:1,eye:P.r3,head:compose(H.hair(R.hair_black,{short:1}),(img,T,ex,ey)=>{ img.set(ex+1,ey+3,P.y3); img.set(ex-1,ey+3,P.y3); }),pad:spikePad(R.dsteel),backItem:(img,T)=>{ banner(img,T); drum(img,T); },deco:loin(R.leather)}};
C.hero_orc_warlord={cell:U,cfg:{anim:'melee',scale:1.12,bulk:1.05,skin:R.orc,torso:R.orc,sleeve:R.orc,pants:R.leather,boots:R.leather,weapon:'blade',twoHand:3,tusks:1,brow:1,head:H.hair(R.hair_black,{topknot:1,short:1}),deco:compose(sash(R.team),loin(R.team,5),(img,T)=>{ line(img,T.tL+2,T.tTop+2,T.tL+4,T.tTop+4,P.o1); line(img,T.tL+6,T.tTop+1,T.tL+7,T.tTop+3,P.o1); }),front:(img,T)=>{ const [x,y]=pt(T.shX,T.shY,1.2,3); img.set(x,y,P.g5); img.set(x+1,y,P.g4); }}};
C.hero_elf_warden={cell:U,cfg:{anim:'melee',scale:1.1,skin:R.elf,torso:R.violet,sleeve:R.violet,pants:R.hair_black,boots:R.grey,belt:R.gold,weapon:'crescent',ear:1,cape:R.violet,capeLong:2,head:H.hood(R.violet,{mask:R.steel,tail:1}),deco:sash(R.team),basePose:{wA:-0.4}}};
// monsters
C.monster_bandit={cell:U,cfg:{anim:'melee',skin:R.skin,torso:R.leather,sleeve:R.leather,pants:R.dark,boots:R.leather,belt:[P.b1,P.b1,P.b2],weapon:'dagger',head:H.hood(R.fur,{mask:R.dark}),bulk:0.9,basePose:{wA:0.2,armA:1.0}}};
C.monster_skeleton={cell:U,cfg:{anim:'melee',skin:R.bone,torso:R.bone,sleeve:R.bone,pants:R.bone,boots:R.bone,limbW:2,weapon:'sword',wOpt:{len:9,blade:R.rust,guard:R.rust},shield:'broken',deco:ribs,head:H.skull,headSquash:0.95}};
C.monster_skeleton_archer={cell:U,cfg:{anim:'bow',skin:R.bone,torso:R.bone,sleeve:R.bone,pants:R.bone,boots:R.bone,limbW:2,weapon:'bow',wOpt:{h:8,broken:1,ramp:[P.b1,P.b2,P.b3]},deco:ribs,head:H.skull}};
C.monster_zombie={cell:U,cfg:{anim:'melee',skin:R.zombie,torso:R.fur,sleeve:R.zombie,pants:R.leather,boots:R.zombie,weapon:null,hunch:2,basePose:{armA:0.1,offA:0.2},head:(img,T,ex,ey)=>{ img.set(ex,ey,P.r3); img.set(ex+1,ey+2,P.DS); img.set(ex,ey+2,P.DS); },deco:(img,T)=>{ for(let i=0;i<T.tw;i+=3) img.set(T.tL+i,T.hipY-1,null); img.set(T.tL+4,T.tTop+3,P.o2); },animOverride:{attack:[{armA:0.1},{armA:-0.6,lean:-1},{armA:-0.9,lean:-1},{armA:0.4,lean:2,dx:1},{armA:0.5,lean:2,dx:1},{armA:0.1}],attack2:[{armA:0.1,offA:0.2},{armA:-1.2,offA:-1.2},{armA:-1.4,offA:-1.4,bob:1},{armA:0.7,offA:0.7,lean:2,dx:2},{armA:0.7,offA:0.7,lean:2,dx:2},{armA:0.1}]}}};
C.monster_troll={cell:U,cfg:{anim:'melee',scale:1.2,skin:R.troll,torso:R.troll,sleeve:R.troll,pants:R.fur,boots:R.troll,weapon:'club',wOpt:{len:12,fat:1.2},tusks:2,ear:1,legLen:1.1,head:H.hair(R.hair_brown,{mohawk:1,noCap:1}),deco:loin(R.fur,5)}};
C.monster_fishman={cell:U,cfg:{anim:'melee',skin:R.fish,torso:R.fish,sleeve:R.fish,pants:R.fish,boots:R.fish,weapon:'spear',wOpt:{len:13},headSquash:0.85,headScale:1.1,eye:P.y3,head:(img,T,ex,ey)=>{ img.set(ex,ey-2,P.g5); img.set(ex+1,ey-2,P.DS); img.set(ex,ey-3,P.t3); img.set(ex+1,ey+2,P.t1); img.set(ex+2,ey+2,P.t1); for(let k=0;k<4;k++) img.set(Math.round(T.hx)-2-k,Math.round(T.hy-T.hr)-1+k,k%2?P.t2:P.t3); },deco:(img,T)=>{ for(let j=2;j<T.tH;j+=2) for(let i=3;i<T.tw-2;i++) img.set(T.tL+i,T.tTop+j,P.n5); },basePose:{wA:-1.3}}};
return C;
