// creatures: quadrupeds, mounts, flyers, specials. expects X,G,HC (humanoid configs). returns {name:{sheet}}
const {P,rng,Img,shadeBlob,line,outline,groundY}=X; const {R,box,strip,pt,humanoid,rotate,ANIM,W}=G;
const dk=r=>[r[0],r[0],r[1],null];
function wing(img,x,y,ang,len,kind,ramp,near){ // ang: direction of wing (up-back ≈ -2.2)
  if(kind==='feather'){ for(let k=0;k<5;k++){ const a=ang+(k-2)*0.22; const L=len*(1-Math.abs(k-2)*0.12); strip(img,x,y,a,0,L,1.2-k*0.1,near?ramp:dk(ramp)); } strip(img,x,y,ang-0.35,0,len*0.55,1.8,near?[ramp[1],ramp[2],ramp[2]]:dk(ramp)); }
  else { const tip=pt(x,y,ang,len); const fingers=[ang+0.55,ang+0.2,ang-0.2]; for(let t=0;t<=len;t+=0.5){ const [bx,by]=pt(x,y,ang,t); strip(img,bx,by,ang+1.9,0,(len-t)*0.55+1,0.6,near?ramp:dk(ramp)); } strip(img,x,y,ang,0,len,0.6,near?[P.b1,P.b2,P.b3]:[P.b1,P.b1,P.b2]); for(const f of fingers){ strip(img,tip[0],tip[1],f+1.7,0,len*0.5,0.4,[P.b1,P.b2,P.b2]); } } }
function quadHead(img,type,hx,hy,S,c,p){ const r=c.headR*S; const ramp=c.headRamp||c.body;
  if(type==='horse'){ strip(img,hx,hy,0.7,0,6*S,2*S,ramp); shadeBlob(img,hx,hy,r,r*0.9,ramp); img.set(hx+1,hy-r-1,ramp[1]); img.set(hx,hy-r-1,ramp[1]); const [mx,my]=pt(hx,hy,0.7,6*S); img.set(mx+1,my,P.DS); img.set(hx+1,hy-1,P.DS); if(c.barding){ for(let t=0;t<5*S;t+=0.5){ const [x,y]=pt(hx,hy-1,0.7,t); img.set(x,y,t<1?P.g5:P.g3);} } return; }
  shadeBlob(img,hx,hy,r*1.05,r*0.9,ramp);
  const ey=Math.round(hy-r*0.2), ex=Math.round(hx+r*0.4);
  if(type==='wolf'||type==='cat'||type==='bear'){ const sl=type==='wolf'?4*S:(type==='bear'?3*S:2*S); box(img,Math.round(hx+r*0.5),Math.round(hy),Math.round(sl),Math.round(r*0.9),ramp); img.set(Math.round(hx+r*0.5+sl-1),Math.round(hy),P.DS);
    if(p.bite){ for(let i=0;i<sl;i++) img.set(Math.round(hx+r*0.5)+i,Math.round(hy+r*0.9),null); img.set(Math.round(hx+r*0.5+sl-2),Math.round(hy+r*0.9)-1,P.g5); }
    const earH=type==='wolf'?3:(type==='cat'?2:1); for(let k=0;k<earH;k++){ img.set(Math.round(hx-r*0.3),Math.round(hy-r)-k,ramp[k?2:1]); img.set(Math.round(hx-r*0.3)+1,Math.round(hy-r)-k+ (k===earH-1?1:0),ramp[1]); }
    img.set(ex,ey,c.eye||P.DS); return; }
  if(type==='eagle'){ const bx=Math.round(hx+r*0.7), by=Math.round(hy); img.set(bx,by,P.y3); img.set(bx+1,by,P.y2); img.set(bx+2,by+1,P.y2); img.set(bx+1,by+1,P.y1); img.set(bx,by-1,P.y3); img.set(ex,ey,P.DS); img.set(Math.round(hx-r),Math.round(hy-r*0.6),ramp[2]); img.set(Math.round(hx-r)-1,Math.round(hy-r*0.9),ramp[2]); return; }
  if(type==='reptile'){ strip(img,hx,hy,0.25,0,r*2.2,r*0.55,ramp); img.set(ex,ey,c.eye||P.y3); const [mx,my]=pt(hx,hy,0.25,r*2.2); img.set(mx,my,P.DS); if(p.bite||p.breath){ for(let t=r;t<r*2.2;t+=0.5){ const [x,y]=pt(hx,hy+r*0.5,0.35,t); img.set(x,y,P.r1);} } for(let k=0;k<3;k++){ img.set(Math.round(hx-r*0.6)-k,Math.round(hy-r)-k,k===2?P.g5:P.g4); } img.set(ex+2,Math.round(hy+r*0.4),P.g5); return; }
}
function quad(c,p,cell){ const img=new Img(cell,cell); const S=c.S||1; const fly=c.fly?6:0; const gy=cell-1-fly+Math.round(p.fall||0);
  const legK=p.legK??1; const legH=Math.round(c.legH*S*legK); const L=c.bodyL*S, Hh=c.bodyH*S; const bx=Math.floor(cell/2)+(p.dx||0)+(c.shift||0); const by=gy-legH-Hh/2+1+(p.bob||0);
  const flap=p.flap??0; const wingA=-2.0+Math.sin(flap)*0.9;
  if(c.wings) wing(img,bx-L*0.05,by-Hh*0.4,wingA-0.25,c.wingL*S,c.wings,c.wingRamp,false);
  // tail
  const tb=[bx-L*0.48,by-Hh*0.1]; const tt=c.tail; const tw=Math.sin((p.phase||0)+ (p.t||0))*0.25;
  if(tt==='bushy') strip(img,tb[0],tb[1],2.6+tw,0,7*S,t=>0.8+t*0.12,c.tailRamp||c.body);
  if(tt==='hair') strip(img,tb[0],tb[1],2.0+tw,0,8*S,t=>0.6+t*0.08,c.tailRamp||c.body);
  if(tt==='tuft'){ strip(img,tb[0],tb[1],2.3+tw,0,8*S,0.4,c.body); const e=pt(tb[0],tb[1],2.3+tw,8*S); shadeBlob(img,e[0],e[1],1.5,1.5,c.tailRamp||c.body); }
  if(tt==='reptile'){ for(let t=0;t<14*S;t+=0.5){ const a=2.9+Math.sin(t/5+(p.t||0))*0.15; const [x,y]=pt(tb[0],tb[1],a,t); strip(img,x,y,a+1.57,-(2.2*S*(1-t/(14*S))+0.5),(2.2*S*(1-t/(14*S))+0.5),0.5,c.body);} const tip=pt(tb[0],tb[1],2.9,14*S); img.set(tip[0],tip[1]-1,P.g4); img.set(tip[0]-1,tip[1],P.g4); }
  if(tt==='stub') shadeBlob(img,tb[0],tb[1],1.5*S,1.5*S,c.body);
  // legs
  const legPos=[[-0.33,-1],[0.33,-1],[-0.33,1],[0.33,1]];
  const ph=p.phase||0;
  const drawLeg=(fx,side,far)=>{ const lx=bx+fx*L+(far?-1:1)*1; const sw=(p.stride!=null?Math.sin(ph+(fx>0?0:Math.PI)+(far?Math.PI:0)):0)*2*S; const tuck=c.fly&&!p.landed; const topY=by+Hh*0.15; let ex2=lx+sw, ey2=gy-(sw>0.5?1:0); if(tuck){ ex2=lx-3*S; ey2=topY+legH*0.8; } const rr=far?dk(c.legRamp||c.body):(c.legRamp||c.body); strip(img,lx,topY,Math.atan2(ey2-topY,ex2-lx),0,Math.hypot(ex2-lx,ey2-topY),c.legW*S/2,rr); if(!tuck){ img.set(ex2,ey2,c.foot||rr[0]); img.set(ex2+1,ey2,c.foot||rr[0]); } };
  if(legK>0){ for(const [fx] of legPos.slice(0,2)) drawLeg(fx,-1,true); }
  shadeBlob(img,bx,by,L/2,Hh/2,c.body.concat([c.bodyHi||null]));
  if(c.belly) for(let x=Math.round(bx-L*0.3);x<bx+L*0.3;x++) img.set(x,Math.round(by+Hh/2-1),c.belly);
  if(c.bodyDeco) c.bodyDeco(img,{bx,by,L,Hh,S,gy,p});
  if(legK>0){ for(const [fx] of legPos.slice(2)) drawLeg(fx,1,false); }
  // neck + head
  const na=(c.neckA??-0.8)+(p.headDown||0); const [nx,ny]=[bx+L*0.38,by-Hh*0.15]; let hx=nx, hy=ny;
  if(c.neck){ strip(img,nx,ny,na,0,c.neck*S,c.neckW*S/2,c.body); [hx,hy]=pt(nx,ny,na,c.neck*S); }
  if(c.headType && c.headType!=='none') quadHead(img,c.headType,hx+(p.lunge||0),hy,S,c,p);
  if(c.mane) for(let t=0;t<c.neck*S;t+=1){ const [x,y]=pt(nx-1,ny-1,na,t); img.set(x-1,y,c.mane[1]); img.set(x-2,y+1,c.mane[0]); }
  if(p.breath){ const [mx,my]=pt(hx,hy,0.25,c.headR*S*2.4); for(let t=0;t<p.breath;t+=0.5){ const w=t*0.35; for(let s2=-w;s2<=w;s2+=0.5){ const [x,y]=pt(mx,my,0.35,t,s2); const q=Math.abs(s2)/(w+0.01); img.set(x,y,t<3?P.r5:(q<0.35?P.r5:(q<0.7?P.r4:P.r3))); } } }
  // rider / centaur torso
  if(c.rider){ const rc=Object.assign({},c.rider.cfg,{noLegs:true}); const rp=Object.assign({},c.rider.base||{},p.rider||{}); const rimg=humanoid(rc,rp,cell,cell); const rS=rc.scale||1; const rLeg=Math.round(7*rS*(rc.legLen||1)); const rHip=cell-1-rLeg+1; const sx=bx+(c.rider.x||0)*L, sy=by-Hh*(c.rider.y??0.45); const ox=Math.round(sx-Math.floor(cell/2)), oy=Math.round(sy-rHip);
    let rim=rimg; if(p.riderRot) rim=rotate(rimg,p.riderRot,Math.floor(cell/2),rHip); for(let y=0;y<cell;y++) for(let x=0;x<cell;x++){ const v=rim.d[y*cell+x]; if(v) img.set(x+ox,y+oy,v);} if(c.saddle) c.saddle(img,{bx,by,L,Hh,S,sx,sy}); if(!c.centaur){ strip(img,sx+1,sy,1.4,0,Hh*0.55,0.9,rc.pants||R.leather); } }
  if(c.wings) wing(img,bx+L*0.05,by-Hh*0.45,wingA,c.wingL*S,c.wings,c.wingRamp,true);
  if(c.front) c.front(img,{bx,by,L,Hh,S,gy,p});
  return img; }
function qSheet(c,cell){ const rows=[]; const riderAnim=c.rider?ANIM[c.rider.cfg.anim||'melee']:null; const fl=c.fly;
  const mk=(p)=>{ const im=quad(c,p,cell); outline(im); return im; };
  const rp=(k,i)=>riderAnim?Object.assign({},riderAnim[k][Math.min(i,riderAnim[k].length-1)]):{};
  rows.push([0,1,2,3].map(i=>mk({bob:i>1?1:0,flap:i/4*6.28,t:i/4*6.28,rider:rp('idle',i)})));
  rows.push([0,1,2,3,4,5].map(i=>{ const ph=i/6*6.2832; return mk({stride:1,phase:ph,bob:i%3===1?-1:0,flap:ph,t:ph,rider:Object.assign(rp('idle',0),{bob:i%3===1?-1:0})}); }));
  const atk=c.attack||[{},{headDown:-0.3,lunge:-1},{headDown:-0.4,lunge:-1,dx:-1},{headDown:0.2,lunge:2,dx:2,bite:1},{headDown:0.2,lunge:2,dx:2,bite:1},{}];
  rows.push(atk.map((a,i)=>mk(Object.assign({flap:i/6*6.28,t:i},a,{rider:rp('attack',i)}))));
  rows.push([0,1].map(i=>mk({dx:-1-i,headDown:-0.3,bob:1,flap:2.5,rider:Object.assign(rp('hurt',i))})));
  const die=[]; for(let i=0;i<6;i++){ const k=i/5; let im=quad(c,{legK:Math.max(0,1-k*1.3),headDown:k*0.9,flap:3.5+k,fall:fl?Math.min(6,k*7):0,riderRot:-k*1.2,rider:Object.assign(rp('hurt',1),{noWeapon:i>2}),landed:1},cell); outline(im); die.push(groundY(im)); } rows.push(die);
  const atk2=c.attack2||[{},{headDown:-0.5,bob:-1},{headDown:-0.6,bob:-2,dx:-1},{headDown:0.3,lunge:3,dx:3,bite:1},{headDown:0.3,lunge:2,dx:2},{}];
  rows.push(atk2.map((a,i)=>mk(Object.assign({flap:i/6*6.28*1.5,t:i},a,{rider:rp('attack2',i)}))));
  const sheet=new Img(cell*6,cell*6); rows.forEach((row,r)=>row.forEach((im,i)=>{ let g=im; if(r!==4){ g=fix(im,fl?6:0);} sheet.blit(g,i*cell,r*cell); })); return sheet; }
function fix(im,hover){ let maxy=-1; for(let y=0;y<im.h;y++) for(let x=0;x<im.w;x++) if(im.d[y*im.w+x]) maxy=Math.max(maxy,y); const dy=im.h-1-hover-maxy; if(!dy||maxy<0) return im; const n=new Img(im.w,im.h); for(let y=0;y<im.h;y++) for(let x=0;x<im.w;x++){ const v=im.d[y*im.w+x]; if(v) n.set(x,y+dy,v);} return n; }
const OUT={};
const WOLF={body:[P.g1,P.g2,P.g3],bodyHi:P.g4,headType:'wolf',headR:3.2,eye:P.y3,neck:2,neckW:4,neckA:-0.7,legH:6,legW:2.4,bodyL:15,bodyH:7,tail:'bushy',foot:P.DS,belly:P.g3,bodyDeco:(img,q)=>{ for(let i=0;i<4;i++) img.set(Math.round(q.bx+q.L*0.1+i*1.5),Math.round(q.by-q.Hh/2)-1+(i%2),P.g2); }};
const BEAR={body:[P.b1,P.b2,P.b3],bodyHi:P.b4,headType:'bear',headR:3.6,neck:1.5,neckW:5,neckA:-0.5,legH:5,legW:3.4,bodyL:17,bodyH:10,tail:'stub',foot:P.b1};
OUT.monster_wolf={cell:48,c:Object.assign({},WOLF)};
OUT.monster_bear={cell:48,c:Object.assign({},BEAR,{attack2:[{},{bob:-2,headDown:-0.4},{bob:-3,headDown:-0.5},{dx:2,lunge:2,bite:1},{dx:2,lunge:2,bite:1},{}]})};
OUT.unit_elf_bear={cell:64,c:Object.assign({},BEAR,{S:1.35,bodyDeco:(img,q)=>{ for(let i=0;i<3;i++){ img.set(Math.round(q.bx-4+i*4),Math.round(q.by-2+(i%2)),P.t3); img.set(Math.round(q.bx-4+i*4)+1,Math.round(q.by-1+(i%2)),P.t2);} },front:(img,q)=>{ const x=Math.round(q.bx+q.L*0.4), y=Math.round(q.by-q.Hh*0.1); for(let k=0;k<5;k++){ img.set(x-1+k%2,y+k-1,k%2?P.m2:P.m3); img.set(x+(k%2?-1:1),y+k,P.n4);} }})};
const HORSE={body:[P.g3,P.g4,P.g5],headType:'horse',headR:2.6,neck:6,neckW:4,neckA:-1.0,legH:9,legW:2.2,bodyL:18,bodyH:9,tail:'hair',tailRamp:[P.g2,P.g3,P.g4],mane:[P.g2,P.g3],foot:P.g1};
const rider=(k)=>({cfg:Object.assign({},k),base:{}});
const HC=HCfg;
OUT.unit_human_knight={cell:64,c:Object.assign({},HORSE,{S:1.15,barding:1,rider:{cfg:Object.assign({},HC.unit_human_footman.cfg,{weapon:'spear',wOpt:{len:18},shield:'kite',deco:null}),base:{armA:0.4,wA:-0.25},x:-0.05,y:0.5},bodyDeco:(img,q)=>{ for(let x=Math.round(q.bx-q.L*0.45);x<q.bx+q.L*0.42;x++) for(let y=Math.round(q.by);y<q.by+q.Hh*0.55;y++) if(img.get(x,y)) img.set(x,y,y===Math.round(q.by)?P.y3:((x+y)%6===0?P.m2:(x<q.bx-q.L*0.2?P.m4:P.m3))); }})};
OUT.unit_orc_wolfrider={cell:64,c:Object.assign({},WOLF,{S:1.45,rider:{cfg:Object.assign({},HC.unit_orc_grunt.cfg,{weapon:'spear',wOpt:{len:14},scale:0.95}),base:{armA:0.5,wA:-0.6},x:-0.05,y:0.45},saddle:(img,q)=>{ for(let i=-3;i<=3;i++){ img.set(q.sx+i,q.sy+2,i<0?P.m4:P.m3); img.set(q.sx+i,q.sy+3,P.m2);} }})};
OUT.hero_orc_farseer={cell:64,c:Object.assign({},WOLF,{S:1.5,body:[P.g2,P.g3,P.g4],rider:{cfg:Object.assign({},HC.unit_orc_shaman.cfg,{weapon:'staff',wOpt:{len:13,top:'gem'},eye:P.t3,head:(img,T,ex,ey)=>{ for(let x=Math.round(T.hx-T.hr);x<=Math.round(T.hx+T.hr)+1;x++) for(let y=Math.round(T.hy-T.hr)-1;y<ey;y++) if(img.get(x,y)||y===ey-1) img.set(x,y,x>T.hx+1?P.g5:P.g4); img.set(ex,ey-1,P.DS); img.set(ex+1,ey-1,P.DS); img.set(Math.round(T.hx)-2,Math.round(T.hy-T.hr)-2,P.g5); },castColor:[P.w3,P.t3]}),x:-0.05,y:0.45},saddle:(img,q)=>{ for(let i=-4;i<=3;i++){ img.set(q.sx+i,q.sy+2,i<0?P.m4:P.m3); img.set(q.sx+i,q.sy+3,P.m2);} }})};
const CAT={body:[P.g3,P.g4,P.g5],headType:'cat',headR:3.2,neck:2,neckW:4,neckA:-0.5,legH:7,legW:2.4,bodyL:18,bodyH:7,tail:'hair',tailRamp:[P.g3,P.g4,P.g5],foot:P.g2,eye:P.t2};
OUT.hero_elf_priestess={cell:64,c:Object.assign({},CAT,{S:1.4,rider:{cfg:Object.assign({},HC.unit_elf_archer.cfg,{torso:[P.g2,P.g3,P.g5],sleeve:[P.g2,P.g3,P.g4],cape:R.team,backItem:null,head:(img,T,ex,ey)=>{ const hr=T.hr; for(let y=Math.round(T.hy-hr);y<T.hy+8;y++) for(let x=Math.round(T.hx-hr)-1;x<T.hx-1;x++) if(img.get(x,y)||y>T.hy) img.set(x,y,x<T.hx-3?P.g5:P.g4); const tx=Math.round(T.hx), ty=Math.round(T.hy-hr)-1; img.set(tx-1,ty,P.g5); img.set(tx-2,ty-1,P.g5); img.set(tx+1,ty,P.g5); img.set(tx+2,ty-1,P.g5); img.set(tx,ty,P.y3); }}),x:-0.05,y:0.45}})};
// centaurs
const DEER={body:[P.b3,P.b4,P.b5],headType:'none',legH:9,legW:2,bodyL:16,bodyH:7,tail:'stub',foot:P.b1,centaur:1};
OUT.unit_elf_dryad={cell:64,c:Object.assign({},DEER,{S:1.3,rider:{cfg:{anim:'melee',skin:[P.o2,P.o3,P.n5],torso:[P.o2,P.o3,P.n5],sleeve:[P.o2,P.o3,P.n5],pants:R.fur,boots:R.fur,weapon:'spear',wOpt:{len:14},ear:1,scale:1.05,head:(img,T,ex,ey)=>{ G.blobClip(img,T.hx-0.5,T.hy-0.6,T.hr+0.8,T.hr+0.3,[P.n2,P.n3,P.n4,null],(x,y)=>y<ey-1||x<ex-3); img.set(Math.round(T.hx)-2,Math.round(T.hy-T.hr)-1,P.n5); img.set(Math.round(T.hx)+1,Math.round(T.hy-T.hr)-1,P.v3); },deco:(img,T)=>{ for(let k=0;k<T.tw;k++){ const y=T.tTop+1+Math.round(k*(T.tH-2)/T.tw); img.set(T.tL+k,y,P.m3); img.set(T.tL+k,y+1,P.m2);} }},base:{wA:-1.1},x:0.36,y:0.45},bodyDeco:(img,q)=>{ for(let i=0;i<4;i++) img.set(Math.round(q.bx-q.L*0.3+i*3),Math.round(q.by-1+(i%2)),P.g5); }})};
OUT.hero_elf_keeper={cell:64,c:Object.assign({},DEER,{S:1.45,body:[P.n2,P.n3,P.n4],rider:{cfg:{anim:'caster',skin:[P.n3,P.n4,P.n5],torso:[P.n1,P.n2,P.n3],sleeve:[P.n2,P.n3,P.n4],pants:R.fur,boots:R.fur,weapon:'staff',wOpt:{len:15,top:'living'},scale:1.15,castColor:[P.t2,P.t3],head:(img,T,ex,ey)=>{ const tx=Math.round(T.hx), ty=Math.round(T.hy-T.hr); for(const sd of [-1,1]){ line(img,tx+sd,ty,tx+sd*3,ty-5,P.b4); line(img,tx+sd*2,ty-3,tx+sd*5,ty-4,P.b4); img.set(tx+sd*3,ty-6,P.b5);} for(let k=0;k<6;k++) img.set(ex-1+(k%3)-1,ey+2+Math.floor(k/3),P.n2); },deco:(img,T)=>{ for(let i=0;i<T.tw;i++){ img.set(T.tL+i,T.tTop,i%2?P.n4:P.n5); img.set(T.tL+i,T.tTop+1,P.n3);} for(let k=0;k<T.tw;k++) img.set(T.tL+k,T.tTop+2+Math.round(k*(T.tH-3)/T.tw),P.m3); }},base:{wA:-1.45},x:0.36,y:0.45}})};
// flyers
const GRIF={body:[P.b3,P.b4,P.b5],headRamp:[P.g4,P.g5,P.g5],headType:'eagle',headR:3,neck:3,neckW:4,neckA:-0.8,legH:6,legW:2.2,bodyL:16,bodyH:8,tail:'tuft',tailRamp:[P.b2,P.b3,P.b4],fly:1,wings:'feather',wingL:16,wingRamp:[P.g3,P.g4,P.g5],foot:P.y2};
OUT.unit_human_griffon={cell:64,c:Object.assign({},GRIF,{S:1.2,rider:{cfg:Object.assign({},HC.hero_human_paladin.cfg,{scale:0.95,cape:null,twoHand:null,weapon:'hammer',wOpt:{len:8}}),x:-0.1,y:0.45},saddle:(img,q)=>{ for(let i=-4;i<=3;i++){ img.set(q.sx+i,q.sy+2,i<0?P.m4:P.m3); img.set(q.sx+i,q.sy+3,P.m2); img.set(q.sx+i,q.sy+4,P.m1);} }})};
OUT.unit_elf_hippogryph={cell:64,c:Object.assign({},GRIF,{S:1.2,body:[P.b3,P.b4,P.b5],headRamp:[P.v2,P.v3,P.g5],wingRamp:[P.v2,P.v3,P.g5],tail:'hair',tailRamp:[P.v1,P.v2,P.v3],rider:{cfg:Object.assign({},HC.unit_elf_archer.cfg,{backItem:null}),x:-0.1,y:0.45},saddle:(img,q)=>{ for(let i=-4;i<=3;i++){ img.set(q.sx+i,q.sy+2,i<0?P.m4:P.m3); img.set(q.sx+i,q.sy+3,P.m2);} }})};
const WYV={body:[P.o1,P.o2,P.o3],headType:'reptile',headR:2.6,neck:5,neckW:3,neckA:-0.9,legH:6,legW:2.4,bodyL:15,bodyH:8,tail:'reptile',fly:1,wings:'bat',wingL:17,wingRamp:[P.b2,P.b3,P.b4],foot:P.DS,belly:P.b4};
OUT.unit_orc_wyvern={cell:64,c:Object.assign({},WYV,{S:1.2,rider:{cfg:Object.assign({},HC.unit_orc_grunt.cfg,{weapon:'spear',wOpt:{len:14},scale:0.9,pad:null,backItem:(img,T)=>{ const x=T.tL, y0=T.tTop-9; for(let y=y0;y<=T.tTop+3;y++) img.set(x,y,P.b3); for(let j=0;j<5;j++) for(let i=1;i<=4;i++) img.set(x-i,y0+1+j,i<2?P.m4:P.m3); }}),base:{armA:0.4,wA:-0.4},x:-0.05,y:0.45}})};
OUT.monster_dragon={cell:96,c:Object.assign({},WYV,{S:2.3,body:[P.r1,P.r2,P.r3],bodyHi:P.r4,belly:P.r5,wingRamp:[P.r1,P.r2,P.r4],headR:2.8,neck:6,wingL:15,legH:6,shift:-6,attack:[{},{headDown:-0.4},{headDown:-0.3,breath:6},{headDown:0.1,breath:18},{headDown:0.15,breath:24},{headDown:0,breath:10}],attack2:[{},{headDown:-0.5,bob:-1},{headDown:-0.6,bob:-2,dx:-1},{headDown:0.3,lunge:3,dx:3,bite:1},{headDown:0.3,lunge:2,dx:2,bite:1},{}]})};
OUT.monster_dragon.c.fly=0; OUT.monster_dragon.c.legH=4; OUT.monster_dragon.c.legW=3.2; OUT.monster_dragon.c.bodyH=9; OUT.monster_dragon.c.bodyL=17;
// specials
function slimeSheet(){ const cell=48; const mk=(sx,sy,o={})=>{ const im=new Img(cell,cell); const rx=9*sx, ry=7*sy; const cx=24+(o.dx||0), cy=47-ry; shadeBlob(im,cx,cy,rx,ry,[P.n3,P.n4,P.n5,P.g5]); for(let y=Math.ceil(cy+ry*0.7);y<48;y++) for(let x=0;x<48;x++) if(im.get(x,y)) im.set(x,y,y>=47?P.n2:im.get(x,y)); const ex=Math.round(cx+rx*0.35), ey=Math.round(cy-ry*0.15); if(!o.dead){ im.set(ex,ey,P.DS); im.set(ex,ey-1,P.DS); im.set(ex-3,ey,P.DS); im.set(ex-3,ey-1,P.DS); if(o.mouth){ im.set(ex-2,ey+2,P.DS); im.set(ex-1,ey+2,P.DS); im.set(ex-1,ey+3,P.r3);} else im.set(ex-1,ey+2,P.n2);} else { im.set(ex,ey,P.n2); im.set(ex-3,ey,P.n2); } im.set(Math.round(cx-rx*0.4),Math.round(cy+ry*0.3),P.n2); outline(im); return fix(im,0); };
  const rows=[[mk(1,1),mk(1.04,0.96),mk(1.08,0.92),mk(1.04,0.96)],[mk(1.1,0.85),mk(1,1),mk(0.88,1.18),mk(0.92,1.1),mk(1,1),mk(1.1,0.85)],[mk(1.2,0.75),mk(1.25,0.7),mk(0.8,1.3,{dx:2,mouth:1}),mk(0.9,1.15,{dx:4,mouth:1}),mk(1.2,0.8,{dx:3,mouth:1}),mk(1,1)],[mk(1.25,0.7,{dx:-1}),mk(1.15,0.8,{dx:-2})],[mk(1.2,0.8),mk(1.35,0.65),mk(1.5,0.5,{dead:1}),mk(1.6,0.4,{dead:1}),mk(1.7,0.3,{dead:1}),mk(1.8,0.22,{dead:1})],[mk(1.3,0.65),mk(1.4,0.6),mk(0.75,1.45,{dx:1,mouth:1}),mk(1.5,0.6,{dx:5,mouth:1}),mk(1.3,0.7,{dx:4}),mk(1,1)]];
  return pack(rows,cell); }
function spiderSheet(){ const cell=48; const mk=(o={})=>{ const im=new Img(cell,cell); const bx=22+(o.dx||0), by=38-(o.bob||0)+(o.drop||0); const lk=o.legK??1; const ph=o.ph||0;
  const legs=[[-0.9,-1],[-0.3,-1],[0.3,-1],[0.9,-1],[-0.9,1],[-0.3,1],[0.3,1],[0.9,1]];
  legs.forEach(([a,side],i)=>{ if(side>0) return; }); const drawLegs=(side)=>legs.forEach(([a,s],i)=>{ if(s!==side) return; const sw=Math.sin(ph+i*1.57)*1.5; const kx=bx+a*6+sw, ky=by-6*lk; const fx=bx+a*11+sw, fy=47-(lk<1?(1-lk)*3:0); const r=side<0?[P.DS,P.DS,P.v1]:[P.DS,P.v1,P.v2]; strip(im,bx+a*2,by,Math.atan2(ky-by,kx-bx-a*2),0,Math.hypot(kx-bx-a*2,ky-by),0.6,r); strip(im,kx,ky,Math.atan2(fy-ky,fx-kx),0,Math.hypot(fx-kx,fy-ky),0.5,r); });
  drawLegs(-1); shadeBlob(im,bx-6,by-3,7,5.5,[P.DS,P.v1,P.v2,P.v3]); im.set(bx-8,by-5,P.r2); im.set(bx-6,by-3,P.r2); im.set(bx-7,by-4,P.r2); shadeBlob(im,bx+4,by-1,4,3.5,[P.DS,P.v1,P.v2,null]); const ex=bx+6, ey=by-2; im.set(ex,ey,P.r3); im.set(ex+1,ey,P.r4); im.set(ex,ey+1,P.r3); im.set(ex-1,ey-1,P.r3); if(o.fang){ im.set(ex+2,ey+2,P.g5); im.set(ex+2,ey+3,P.g5);} drawLegs(1); outline(im); return o.noFix?im:fix(im,0); };
  const rows=[[mk(),mk({bob:1}),mk({bob:1}),mk()],[0,1,2,3,4,5].map(i=>mk({ph:i/6*6.28})),[mk(),mk({dx:-1,bob:2}),mk({dx:-2,bob:3}),mk({dx:3,fang:1}),mk({dx:3,fang:1}),mk()],[mk({dx:-1,bob:1}),mk({dx:-2})],[0,1,2,3,4,5].map(i=>{ const im=mk({legK:1-i*0.18,drop:i,noFix:1}); return groundY(im); }),[mk(),mk({bob:3}),mk({bob:5,dx:-1}),mk({dx:4,fang:1,bob:1}),mk({dx:4,fang:1}),mk()]];
  return pack(rows,cell); }
function wispSheet(){ const cell=48; const mk=(o={})=>{ const im=new Img(cell,cell); const cx=24, r=(o.r||4)+(o.pulse||0); const cy=47-4-r-(o.bob||0); shadeBlob(im,cx,cy,r,r,[P.t2,P.t3,P.w5,P.g5],{rim:false}); const n=3; for(let k=0;k<n;k++){ const a=(o.t||0)+k*2.094; const x=cx+Math.cos(a)*(r+4), y=cy+Math.sin(a)*(r+2); im.set(x,y,P.v3); im.set(x+1,y,P.v2);} if(o.tail) for(let k=1;k<4;k++) im.set(cx-r-k,cy+k*0.5,k<2?P.t3:P.t2); outline(im); return o.noFix?im:fix(im,4); };
  const rows=[[0,1,2,3].map(i=>mk({t:i*1.57,bob:i%2})),[0,1,2,3,4,5].map(i=>mk({t:i*1.05,bob:i%2,tail:1})),[0,1,2,3,4,5].map(i=>mk({t:i*1.05,pulse:[0,1,2,2,1,0][i],r:4})),[mk({r:3.5,t:1}),mk({r:3,t:2})],[0,1,2,3,4,5].map(i=>{ const im=mk({r:Math.max(1,4-i*0.7),t:i,noFix:1}); return groundY(im); }),[0,1,2,3,4,5].map(i=>mk({t:i*1.3,pulse:[0,1,3,3,1,0][i]}))];
  return pack(rows,cell); }
function pack(rows,cell){ const sheet=new Img(cell*6,cell*6); rows.forEach((row,r)=>row.forEach((im,i)=>sheet.blit(im,i*cell,r*cell))); return sheet; }
// humanoid-rig large creatures
const LH={};
LH.unit_orc_ogre={cell:64,cfg:{anim:'melee',scale:1.6,bulk:1.25,headScale:0.85,skin:[P.s1,P.s2,P.s3],torso:[P.s1,P.s2,P.s3],sleeve:[P.s1,P.s2,P.s3],pants:R.fur,boots:R.leather,belt:R.leather,weapon:'club',wOpt:{len:13,fat:1.3,spikes:1},tusks:1,brow:1,deco:(img,T)=>{ shadeBlob(img,T.tL+T.tw*0.6,T.hipY-4,T.tw*0.42,4.5,[P.s1,P.s2,P.s3,null]); const x0=T.tL+Math.floor(T.tw/2)-2; for(let j=0;j<6;j++) for(let i=0;i<6-Math.floor(j/2);i++) img.set(x0+i,T.hipY+j,i===0?P.m4:(i>3?P.m2:P.m3)); }}};
LH.monster_golem={cell:64,cfg:{anim:'melee',scale:1.65,bulk:1.6,headScale:0.7,limbW:4,skin:R.grey,torso:R.grey,sleeve:R.grey,pants:R.grey,boots:R.dsteel,weapon:null,eye:P.t3,deco:(img,T)=>{ line(img,T.tL+3,T.tTop+2,T.tL+6,T.tTop+7,P.t2); line(img,T.tL+6,T.tTop+7,T.tL+5,T.tTop+11,P.t3); line(img,T.tL+10,T.tTop+3,T.tL+12,T.tTop+6,P.t3); for(let k=0;k<4;k++) img.set(T.tL+2+k*4,T.tTop,P.g4); },pad:(img,T)=>shadeBlob(img,T.shX,T.shY-1,4,3.5,[P.g1,P.g2,P.g3,P.g4]),animOverride:{attack:[{armA:1.2},{armA:-1.5,lean:-1},{armA:-2.0,lean:-1},{armA:0.3,lean:2,dx:2},{armA:0.4,lean:2,dx:2},{armA:1.2}]}}};
LH.unit_elf_treant={cell:64,cfg:{anim:'melee',scale:1.6,bulk:1.2,limbW:4,headScale:0.85,skin:R.wood,torso:R.wood,sleeve:[P.b1,P.b2,P.b3],pants:R.wood,boots:[P.b1,P.b1,P.b2],eye:P.t3,weapon:null,headBack:(img,T)=>{ const cx=T.hx-1, cy=T.hy-T.hr-4; for(const [dx,dy,r] of [[-5,2,5],[4,1,5],[0,-2,6],[-2,4,4]]) shadeBlob(img,cx+dx,cy+dy,r,r*0.8,[P.n2,P.n3,P.n4,P.n5]); img.set(cx-3,cy-3,P.v3); img.set(cx+4,cy,P.v3); img.set(cx+1,cy-5,P.v3); img.set(cx+5,cy-3,P.m3); img.set(cx+6,cy-3,P.m4); img.set(cx+6,cy-2,P.m2); },head:(img,T,ex,ey)=>{ img.set(ex+1,ey+2,P.b1); img.set(ex,ey+2,P.b1); img.set(ex-1,ey-1,P.b1); },deco:(img,T)=>{ for(let j=0;j<T.tH;j+=3) img.set(T.tL+2+(j%2),T.tTop+j,P.b2); for(let i=2;i<T.tw-2;i+=4) img.set(T.tL+i,T.tTop+1,P.n4); },front:(img,T)=>{ const [x,y]=pt(T.shX,T.shY,T.p.armA??1.2,6.5*T.S); line(img,x,y,x+2,y+2,P.b2); line(img,x,y,x+3,y,P.b2); line(img,x,y,x+1,y+3,P.b2); }}};
LH.monster_harpy={cell:48,cfg:{anim:'melee',hover:6,skin:R.skin,torso:[P.b2,P.b3,P.b4],sleeve:R.skin,pants:[P.b2,P.b3,P.b4],boots:[P.y1,P.y2,P.y2],legLen:0.7,weapon:null,head:H2hair(),backItem:(img,T)=>{ const a=-2.1+Math.sin((T.p.t||T.p.phase||0)+(T.p.bob||0))*0.7; wing(img,T.tL+3,T.tTop+2,a,13,'feather',[P.b2,P.b3,P.b5],true); },animOverride:{attack:[{armA:1.0,t:0},{armA:-1.2,lean:-1,t:1},{armA:-1.5,lean:-1,t:2},{armA:0.5,lean:2,dx:2,t:3},{armA:0.6,lean:2,dx:2,t:4},{armA:1.0,t:5}]}}};
function H2hair(){ return (img,T,ex,ey)=>{ G.blobClip(img,T.hx-0.4,T.hy-0.6,T.hr+0.5,T.hr+0.2,[P.v1,P.v2,P.v3,null],(x,y)=>y<ey-1||(x<ex-3&&y<ey+5)); for(let k=0;k<5;k++) img.set(Math.round(T.hx-T.hr)-1,Math.round(T.hy)+k,P.v2); }; }
for(const [n,v] of Object.entries(OUT)) OUT[n]={cell:v.cell,sheet:qSheet(v.c,v.cell)};
OUT.monster_slime={cell:48,sheet:slimeSheet()}; OUT.monster_spider={cell:48,sheet:spiderSheet()}; OUT.unit_elf_wisp={cell:48,sheet:wispSheet()};
for(const [n,v] of Object.entries(LH)) OUT[n]={cell:v.cell,sheet:G.buildSheet(v.cfg,v.cell)};
return OUT;
