//! Audio: sounds, playback commands and a software mixer, independent of the output device.
//!
//! Games talk to [`Audio`] (on [`crate::Context`]): add sounds, then `play`, `play_at` (panned
//! and attenuated by position on screen) or `play_music`. The runtime drains the commands each
//! frame into a backend: natively a device stream fed by [`Mixer`], on the web WebAudio nodes.
//! Sounds can be decoded from WAV or generated by [`crate::synth`].

use std::sync::Arc;

use glam::Vec3;

use crate::Camera;

/// Mono samples in -1..1.
#[derive(Clone, Debug, PartialEq)]
pub struct Sound {
    pub samples: Arc<Vec<f32>>,
    pub rate: u32,
}

impl Sound {
    pub fn new(samples: Vec<f32>, rate: u32) -> Self {
        Sound { samples: Arc::new(samples), rate }
    }

    pub fn duration(&self) -> f32 {
        self.samples.len() as f32 / self.rate.max(1) as f32
    }

    /// Decode a PCM WAV file (8/16/24/32-bit integer or 32-bit float, any channel count; mixed
    /// down to mono).
    pub fn from_wav(bytes: &[u8]) -> Result<Sound, String> {
        let u16le = |b: &[u8], o: usize| u16::from_le_bytes([b[o], b[o + 1]]);
        let u32le = |b: &[u8], o: usize| u32::from_le_bytes([b[o], b[o + 1], b[o + 2], b[o + 3]]);
        if bytes.len() < 12 || &bytes[0..4] != b"RIFF" || &bytes[8..12] != b"WAVE" {
            return Err("not a WAV file".into());
        }
        let (mut fmt, mut data) = (None, None);
        let mut o = 12;
        while o + 8 <= bytes.len() {
            let id = &bytes[o..o + 4];
            let len = u32le(bytes, o + 4) as usize;
            let body = &bytes[o + 8..(o + 8 + len).min(bytes.len())];
            match id {
                b"fmt " => fmt = Some(body),
                b"data" => data = Some(body),
                _ => {}
            }
            o += 8 + len + (len & 1);
        }
        let fmt = fmt.ok_or("missing fmt chunk")?;
        let data = data.ok_or("missing data chunk")?;
        if fmt.len() < 16 {
            return Err("short fmt chunk".into());
        }
        let format = u16le(fmt, 0);
        let channels = u16le(fmt, 2).max(1) as usize;
        let rate = u32le(fmt, 4);
        let bits = u16le(fmt, 14) as usize;
        let bytes_per = bits / 8;
        if bytes_per == 0 {
            return Err("bad bit depth".into());
        }
        let frame = bytes_per * channels;
        let sample = |s: &[u8]| -> f32 {
            match (format, bits) {
                (3, 32) => f32::from_le_bytes([s[0], s[1], s[2], s[3]]),
                (_, 8) => (s[0] as f32 - 128.0) / 128.0,
                (_, 16) => i16::from_le_bytes([s[0], s[1]]) as f32 / 32768.0,
                (_, 24) => (((s[2] as i32) << 24 | (s[1] as i32) << 16 | (s[0] as i32) << 8) >> 8) as f32 / 8_388_608.0,
                (_, 32) => i32::from_le_bytes([s[0], s[1], s[2], s[3]]) as f32 / 2_147_483_648.0,
                _ => 0.0,
            }
        };
        let samples = data
            .chunks_exact(frame)
            .map(|f| f.chunks_exact(bytes_per).map(sample).sum::<f32>() / channels as f32)
            .collect();
        Ok(Sound::new(samples, rate))
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct SoundId(pub u32);

/// A playback request.
#[derive(Clone, Debug, PartialEq)]
pub enum AudioCmd {
    Play { sound: SoundId, volume: f32, pan: f32, pitch: f32 },
    Music { sound: Option<SoundId>, volume: f32 },
    Master { volume: f32 },
}

/// The game-facing audio API. Cheap to call every frame; the runtime does the playing.
#[derive(Debug)]
pub struct Audio {
    sounds: Vec<Sound>,
    commands: Vec<AudioCmd>,
    pub sfx_volume: f32,
    pub music_volume: f32,
    master: f32,
    muted: bool,
    music: Option<SoundId>,
    /// Set by the runtime once the output is running (browsers need a click first).
    pub unlocked: bool,
    /// Played automatically whenever a UI button is clicked.
    pub ui_click: Option<SoundId>,
}

impl Default for Audio {
    fn default() -> Self {
        Audio {
            sounds: Vec::new(),
            commands: Vec::new(),
            sfx_volume: 0.8,
            music_volume: 0.5,
            master: 1.0,
            muted: false,
            music: None,
            unlocked: false,
            ui_click: None,
        }
    }
}

impl Audio {
    pub fn add(&mut self, sound: Sound) -> SoundId {
        self.sounds.push(sound);
        SoundId(self.sounds.len() as u32 - 1)
    }

    pub fn sound(&self, id: SoundId) -> &Sound {
        &self.sounds[id.0 as usize]
    }

    pub fn sounds(&self) -> &[Sound] {
        &self.sounds
    }

    pub fn play(&mut self, sound: SoundId) {
        self.play_ex(sound, 1.0, 0.0, 1.0);
    }

    /// `volume` 0..1, `pan` -1 (left) .. 1 (right), `pitch` playback rate (1 = normal).
    pub fn play_ex(&mut self, sound: SoundId, volume: f32, pan: f32, pitch: f32) {
        if self.muted {
            return;
        }
        self.commands.push(AudioCmd::Play {
            sound,
            volume: (volume * self.sfx_volume).clamp(0.0, 2.0),
            pan: pan.clamp(-1.0, 1.0),
            pitch: pitch.clamp(0.1, 4.0),
        });
    }

    /// Play a sound at a world position: panned by where it is on screen, quieter off screen.
    pub fn play_at(&mut self, sound: SoundId, pos: Vec3, camera: &Camera) {
        let s = camera.world_to_screen(pos);
        let v = camera.viewport;
        let x = ((s.x - v.x) / v.w.max(1.0)) * 2.0 - 1.0;
        let y = ((s.y - v.y) / v.h.max(1.0)) * 2.0 - 1.0;
        let off = (x.abs().max(y.abs()) - 1.0).max(0.0);
        let volume = 1.0 / (1.0 + off * 3.0).powi(2);
        if volume > 0.02 {
            self.play_ex(sound, volume, x * 0.8, 1.0);
        }
    }

    /// Start (or switch) looping background music; `None` stops it.
    pub fn play_music(&mut self, sound: Option<SoundId>) {
        if self.music == sound {
            return;
        }
        self.music = sound;
        let volume = if self.muted { 0.0 } else { self.music_volume };
        self.commands.push(AudioCmd::Music { sound, volume });
    }

    pub fn music(&self) -> Option<SoundId> {
        self.music
    }

    pub fn set_muted(&mut self, muted: bool) {
        self.muted = muted;
        self.commands.push(AudioCmd::Master { volume: if muted { 0.0 } else { self.master } });
    }

    pub fn muted(&self) -> bool {
        self.muted
    }

    pub fn set_master(&mut self, v: f32) {
        self.master = v.clamp(0.0, 1.0);
        if !self.muted {
            self.commands.push(AudioCmd::Master { volume: self.master });
        }
    }

    /// Taken by the runtime each frame.
    pub fn drain(&mut self) -> Vec<AudioCmd> {
        std::mem::take(&mut self.commands)
    }
}

struct Voice {
    sound: Sound,
    pos: f64,
    step: f64,
    gain_l: f32,
    gain_r: f32,
    looping: bool,
}

/// A software mixer: voices in, interleaved stereo out. Used by native backends (and tests).
pub struct Mixer {
    rate: u32,
    voices: Vec<Voice>,
    music: Option<Voice>,
    master: f32,
    /// Most simultaneous sound effects; the oldest is dropped beyond this.
    pub max_voices: usize,
}

fn pan_gains(volume: f32, pan: f32) -> (f32, f32) {
    // Constant-power panning.
    let a = (pan.clamp(-1.0, 1.0) + 1.0) * std::f32::consts::FRAC_PI_4;
    (volume * a.cos(), volume * a.sin())
}

impl Mixer {
    pub fn new(rate: u32) -> Self {
        Mixer { rate, voices: Vec::new(), music: None, master: 1.0, max_voices: 32 }
    }

    pub fn active_voices(&self) -> usize {
        self.voices.len()
    }

    pub fn apply(&mut self, cmd: &AudioCmd, sounds: &[Sound]) {
        match cmd {
            AudioCmd::Play { sound, volume, pan, pitch } => {
                let Some(s) = sounds.get(sound.0 as usize) else { return };
                if self.voices.len() >= self.max_voices {
                    self.voices.remove(0);
                }
                let (l, r) = pan_gains(*volume, *pan);
                let step = s.rate as f64 / self.rate as f64 * *pitch as f64;
                self.voices.push(Voice { sound: s.clone(), pos: 0.0, step, gain_l: l, gain_r: r, looping: false });
            }
            AudioCmd::Music { sound, volume } => {
                self.music = sound.and_then(|id| sounds.get(id.0 as usize)).map(|s| {
                    let (l, r) = pan_gains(*volume, 0.0);
                    Voice {
                        sound: s.clone(),
                        pos: 0.0,
                        step: s.rate as f64 / self.rate as f64,
                        gain_l: l,
                        gain_r: r,
                        looping: true,
                    }
                });
            }
            AudioCmd::Master { volume } => self.master = *volume,
        }
    }

    /// Fill `out` (interleaved stereo) with the mix.
    pub fn render(&mut self, out: &mut [f32]) {
        out.fill(0.0);
        let mix = |v: &mut Voice, out: &mut [f32]| -> bool {
            let data = &v.sound.samples;
            let n = data.len();
            if n == 0 {
                return false;
            }
            for frame in out.as_chunks_mut::<2>().0 {
                let i = v.pos as usize;
                if i + 1 >= n {
                    if v.looping {
                        v.pos -= (n - 1) as f64;
                        continue;
                    }
                    return false;
                }
                let f = (v.pos - i as f64) as f32;
                let s = data[i] + (data[i + 1] - data[i]) * f;
                frame[0] += s * v.gain_l;
                frame[1] += s * v.gain_r;
                v.pos += v.step;
            }
            true
        };
        self.voices.retain_mut(|v| mix(v, out));
        if let Some(m) = &mut self.music
            && !mix(m, out)
        {
            self.music = None;
        }
        for s in out.iter_mut() {
            // Soft clip so many overlapping sounds never crackle.
            *s = (*s * self.master).tanh();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mixer_plays_pans_and_finishes() {
        let sounds = vec![Sound::new(vec![0.5; 100], 1000)];
        let mut m = Mixer::new(1000);
        m.apply(&AudioCmd::Play { sound: SoundId(0), volume: 1.0, pan: -1.0, pitch: 1.0 }, &sounds);
        let mut buf = vec![0.0; 100];
        m.render(&mut buf);
        assert!(buf[0] > 0.4 && buf[1].abs() < 1e-3, "hard left: {:?}", &buf[..2]);
        m.render(&mut buf);
        m.render(&mut buf);
        assert_eq!(m.active_voices(), 0);
        m.apply(&AudioCmd::Music { sound: Some(SoundId(0)), volume: 1.0 }, &sounds);
        for _ in 0..10 {
            m.render(&mut buf);
        }
        assert!(buf.iter().any(|s| *s > 0.1), "music loops");
    }

    #[test]
    fn wav_decode() {
        // 16-bit mono, 3 samples.
        let mut w = Vec::new();
        let data: [i16; 3] = [0, 16384, -16384];
        w.extend_from_slice(b"RIFF");
        w.extend_from_slice(&(36u32 + 6).to_le_bytes());
        w.extend_from_slice(b"WAVEfmt ");
        w.extend_from_slice(&16u32.to_le_bytes());
        w.extend_from_slice(&1u16.to_le_bytes());
        w.extend_from_slice(&1u16.to_le_bytes());
        w.extend_from_slice(&8000u32.to_le_bytes());
        w.extend_from_slice(&16000u32.to_le_bytes());
        w.extend_from_slice(&2u16.to_le_bytes());
        w.extend_from_slice(&16u16.to_le_bytes());
        w.extend_from_slice(b"data");
        w.extend_from_slice(&6u32.to_le_bytes());
        for s in data {
            w.extend_from_slice(&s.to_le_bytes());
        }
        let s = Sound::from_wav(&w).unwrap();
        assert_eq!(s.rate, 8000);
        assert_eq!(s.samples.len(), 3);
        assert!((s.samples[1] - 0.5).abs() < 1e-3);
    }
}
